apiVersion: apps/v1
kind: Deployment
metadata:
  name: webclues-app
  labels:
    app: webclues-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: webclues-app
  template:
    metadata:
      labels:
        app: webclues-app
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          requests:
            cpu: 300m
            memory: 256Mi
          limits:
            cpu: 300m
            memory: 256Mi

